version: '3.8'

services:
  web:
    build: .        
    ports:
      - "8000:8000"    
    env_file:
      - .env
    # volumes:
    #   - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=aws_rds.settings 