version: '3.8'

services:
  web:
    image: sknetworks/aws_rds:latest
    ports:
      - "8000:8000"    
    env_file:
      - .env    
    environment:
      - DJANGO_SETTINGS_MODULE=aws_rds.settings 